<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26315" started-at="2020-08-05T19:09:05Z" finished-at="2020-08-05T19:09:32Z">
    <groups>
      <group name="Regression">
        <method signature="assetDetailsTest.ASST027STP(java.lang.String)[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="ASST027STP" class="com.vrt.testcases.assetDetailsTest"/>
        <method signature="assetDetailsTest.ASST028STP()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="ASST028STP" class="com.vrt.testcases.assetDetailsTest"/>
      </group> <!-- Regression -->
    </groups>
    <test name="Default test" duration-ms="26315" started-at="2020-08-05T19:09:05Z" finished-at="2020-08-05T19:09:32Z">
      <class name="com.vrt.testcases.assetDetailsTest">
        <test-method status="PASS" signature="PreSetup()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="PreSetup" is-config="true" duration-ms="88" started-at="2020-08-05T19:09:05Z" finished-at="2020-08-05T19:09:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PreSetup -->
        <test-method status="FAIL" signature="ASST027STP(java.lang.String)[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="ASST027STP" duration-ms="0" started-at="2020-08-05T19:09:05Z" description="Verify the edit setup functionality" data-provider="ASST027STP" finished-at="2020-08-05T19:09:05Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.vrt.testcases.assetDetailsTest.ASST027STP(java.lang.String) throws java.lang.InterruptedException,java.io.IOException,java.awt.AWTException,java.text.ParseException requires a @DataProvider named : ASST027STP in class com.vrt.utility.assetCreationUtility]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.vrt.testcases.assetDetailsTest.ASST027STP(java.lang.String) throws java.lang.InterruptedException,java.io.IOException,java.awt.AWTException,java.text.ParseException requires a @DataProvider named : ASST027STP in class com.vrt.utility.assetCreationUtility
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ASST027STP -->
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="Setup" is-config="true" duration-ms="10380" started-at="2020-08-05T19:09:05Z" finished-at="2020-08-05T19:09:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="ASST028STP()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="ASST028STP" duration-ms="15457" started-at="2020-08-05T19:09:16Z" description="Verify if Audit trial record exists for edit setup" finished-at="2020-08-05T19:09:31Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 3, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.vrt.pages.AuditPage.get_Actiontext(AuditPage.java:97)
at com.vrt.testcases.assetDetailsTest.ASST028STP(assetDetailsTest.java:841)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ASST028STP -->
        <test-method status="PASS" signature="Teardown(org.testng.ITestResult)[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="Teardown" is-config="true" duration-ms="82" started-at="2020-08-05T19:09:31Z" finished-at="2020-08-05T19:09:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ASST028STP status=FAILURE method=assetDetailsTest.ASST028STP()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
        <test-method status="PASS" signature="endReport_releaseMomory()[pri:0, instance:com.vrt.testcases.assetDetailsTest@3632be31]" name="endReport_releaseMomory" is-config="true" duration-ms="281" started-at="2020-08-05T19:09:31Z" finished-at="2020-08-05T19:09:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport_releaseMomory -->
      </class> <!-- com.vrt.testcases.assetDetailsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
